### PR TITLE
Install latest testInfra version and various fixes

### PR DESCRIPTION
**Pull request by justin-stephenson**
This PR is a workaround for the CI failure, I tested this successfully locally.
~~~
    ____________________ ERROR collecting tests/test_default.py ____________________
    tests/test_default.py:6: in <module>
        os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')
    /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/testinfra/utils/ansible_runner.py:153: in __init__
        self.cli.options = self.cli.base_parser(
    E   AttributeError: 'PlaybookCLI' object has no attribute 'base_parser'
~~~

The bug is discussed here:
https://github.com/ansible/molecule/issues/1727
https://github.com/philpep/testinfra/issues/401

The fix is in `testInfra` 3.0.0+ versions however the CI virtualenv pip installed `molecule` requires **testinfra==1.19.0** which leads to this bug.

Alternatively, we could wait for the updated `molecule(2.21?)`/`testinfra(3.0.0)` version to be pulled in automatically and CI will be temporarily broken until that happens. If that makes more sense then we can just close this PR.

### CODE REVIEW

**Comment by justin-stephenson** [comment]
The CI Failure here will be fixed in https://github.com/nkinder/session-recording/pull/8

**Comment by justin-stephenson** [comment]
This should be good to go now, I combined the 2 PRs into this one.

**Comment by justin-stephenson** [comment]
@nkinder Would you mind merging this now that it passes CI ? Thank you!
